"""Extract the basket definitions and calculations from the legacy page.

This is a migration aid, not part of the deployed runtime. Run after edits to
the legacy formulas, then review the generated diff and parity fixtures.
"""
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "pages/1_ADFM_Public_Equities_Baskets.py").read_text()
tree = ast.parse(source)
lines = source.splitlines(keepends=True)
parts = [
    '"""Native basket calculations extracted from the active Streamlit page.\n',
    'Generated by scripts/extract_baskets_engine.py; no Streamlit runtime.\n"""\n',
    "import os\n",
]
for node in tree.body:
    if node.lineno >= 2460:
        break
    if isinstance(node, ast.Import) and any(alias.name == "streamlit" for alias in node.names):
        continue
    if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("adfm_core"):
        continue
    if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
        call = node.value.func
        if isinstance(call, ast.Attribute) and isinstance(call.value, ast.Name) and call.value.id == "st":
            continue
    if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "PASTEL" for t in node.targets):
        continue
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        start = node.lineno
        if node.decorator_list:
            start = node.decorator_list[-1].end_lineno + 1
        parts.extend(lines[start - 1:node.end_lineno])
    else:
        parts.extend(lines[node.lineno - 1:node.end_lineno])
    parts.append("\n")
output = ROOT / "adfm_engine/baskets_legacy_math.py"
output.write_text("".join(parts).replace('CACHE_DIR = Path(".adfm_cache")', 'CACHE_DIR = Path(os.getenv("ADFM_DATA_DIR", "/tmp/adfm-data")) / "basket-cache"'))
ast.parse(output.read_text())
print(output)
